version: 2
jobs:
  build:
    docker:
#      - image: circleci/node:7.10.1-browsers
      - image: circleci/node:10.11
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: node --version
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
